### ISSUE TITLE
Problems with getting lldp neighbors

### ISSUE THREAD

**Issue by pnikolskii** [napalm-automation-community/napalm-ros#106]
### napalm-ros version
```
napalm-ros==1.2.0
```
### ROS version
```
routeros  7.5 
```
### librouteros version
```
librouteros==3.2.1
```
### python version
```
Python 3.10.6
```
### Steps to Reproduce the Issue

When trying to use print(device.get_lldp_neighbors()) error is shown

### Error Traceback
```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
Connecting to #### on port 8728 as ####
Opening ...
Traceback (most recent call last):
  File "/home/projects/pyrostest/lldp.py", line 19, in <module>
    print(device.get_lldp_neighbors())
  File "/usr/local/lib/python3.10/dist-packages/napalm_ros-1.2.0-py3.10.egg/napalm_ros/ros.py", line 256, in get_lldp_neighbors
KeyError: 'interface-name'
```

I also tried print(device.get_lldp_neighbors_detail()) and it works as expected, so it may be not so critical problem, but netbox module for ROS uses print(device.get_lldp_neighbors())

**Comment by luqasz** [comment]
@pnikolskii  Can you show the output of `/ip/neighbor/print` ?

**Comment by pnikolskii** [comment]
> @pnikolskii Can you show the output of `/ip/neighbor/print` ?

```
Columns: INTERFACE, ADDRESS, MAC-ADDRESS, IDENTITY, VERSION, BOARD
 #  INTERFACE       ADDRESS         MAC-ADDRESS        IDENTITY                                                                                                                 VERSION                                      BOARD
 0  ether1          192.168.12.22   48:8F:5A:6D:C0:62  ###-2F-11-SW1                                                                                                            7.5 (stable) Aug/30/2022 09:25:53            CRS328-24P-4S+
    Bridge-LAN
 1  ether1          192.168.12.64   48:8F:5A:20:B8:2D  ###-2f11-AP                                                                                                              7.5 (stable) Aug/30/2022 09:25:53            RBcAPGi-5acD2nD
    Bridge-LAN
 2  ether2          192.168.12.20   74:4D:28:D3:5F:78  ###-2F-1-SW1                                                                                                             7.5 (stable) Aug/30/2022 09:25:53            CRS328-24P-4S+
    Bridge-LAN
 3  ether2          192.168.12.21   C4:AD:34:73:09:9B  ###-2F-7-SW1                                                                                                             7.4.1 (stable) Aug/04/2022 11:48:11          CRS112-8P-4S
    Bridge-LAN
 4  ether2          192.168.12.69   C4:AD:34:5C:04:68  ###-2F-1-AP                                                                                                              7.5 (stable) Aug/30/2022 09:25:53            RBcAPGi-5acD2nD
    Bridge-LAN
 5  ether2          192.168.12.130  D4:CA:6D:07:32:4C  Test\                                                                                                                    7.6beta7 (development) Sep/16/2022 06:27:32  RB951G-2HnD
    Bridge-LAN
 6  ether3                          00:04:13:75:1A:A4  snom715
    Bridge-LAN
 7  ether5-WAN                      70:4F:57:F9:51:CB  ###a1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
    Bridge-LAN
 8  ether5-WAN      192.168.12.62   6C:3B:6B:14:56:33  ###-1F35-AP                                                                                                              7.3.1 (stable) Jun/09/2022 08:58:15          RB941-2nD
    Bridge-LAN
 9  ether5-WAN      192.168.12.65   6C:3B:6B:14:57:C1  ###-2F-24-AP                                                                                                             7.4.1 (stable) Aug/04/2022 11:48:11          RB941-2nD
    Bridge-LAN
10  ether5-WAN      192.168.12.66   64:D1:54:61:6F:91  ###-1F-LAB-AP                                                                                                            7.4.1 (stable) Aug/04/2022 11:48:11          RB941-2nD
    Bridge-LAN
11  ether5-WAN      192.168.12.67   2C:C8:1B:9F:85:7B  ###-1f29-ap                                                                                                              7.5 (stable) Aug/30/2022 09:25:53            RBcAPGi-5acD2nD
    Bridge-LAN
12  ether6          10.2.1.55       64:16:7F:A4:07:4C  Polycom VVX 400
    Bridge-LAN
13  ether8                          00:04:13:75:1A:98  snom715
    Bridge-LAN
14  ether8                          00:04:13:A5:26:2F  snom715
    Bridge-LAN
15  ether8          192.168.12.7    00:04:F2:9E:47:9A  Lync Phone Edition - 9e479a
    Bridge-LAN
16  ether8          192.168.12.61   6C:3B:6B:16:8F:53  ###-2F-27-AP                                                                                                             7.4.1 (stable) Aug/04/2022 11:48:11          RB941-2nD
    Bridge-LAN
17  ether9                          00:04:13:74:A6:64  snom710
    Bridge-LAN
18  ether9                          00:04:13:74:C2:17  snom710
    Bridge-LAN
19  ether9                          00:04:13:75:44:0C  snom715
    Bridge-LAN
20  ether9                          00:04:13:A5:26:FB  snom715
    Bridge-LAN
21  ether9                          00:04:13:A5:27:9C  snom715
    Bridge-LAN
22  ether9          192.168.12.63   6C:3B:6B:14:55:F0  ###-2F-12-AP                                                                                                             7.4.1 (stable) Aug/04/2022 11:48:11          RB941-2nD
    Bridge-LAN
23  ipip-###  10.1.1.41                          ###-gw1                                                                                                                  7.5 (stable) Aug/30/2022 09:25:53            RB750Gr3
24  ipip-###   10.1.1.53                          ###-gw1                                                                                                                 7.5 (stable) Aug/30/2022 09:25:53            RB750Gr3
25  vlan2-2ndWAN                    74:4D:28:D3:5F:61  ###-2F-1-SW1                                                                                                             7.5 (stable) Aug/30/2022 09:25:53            CRS328-24P-4S+
26  vlan2-2ndWAN    10.50.50.1      CC:2D:E0:DB:7E:30  ###-GW2                                                                                                                  7.5 (stable) Aug/30/2022 09:25:53            RBwAPR-2nD
```

**Comment by luqasz** [comment]
Sorry `/ip/neighbor/print detail` since it will print in a key-value pair without table.

**Comment by pnikolskii** [comment]
Good day!
```
# oct/16/2022 17:48:42 by RouterOS 7.5
# software id = ###
#
 0 interface=ether1,Bridge-LAN address=192.168.12.22 address4=192.168.12.22 
   mac-address=48:8F:5A:6D:C0:62 identity="###-2F-11-SW1" platform="MikroTik" 
   version="7.5 (stable) Aug/30/2022 09:25:53" unpack=none age=50s 
   uptime=3w2d10h35m49s software-id="SD8X-BJQ4" board="CRS328-24P-4S+" 
   interface-name="bridge/ether3" 
   system-description="MikroTik RouterOS 7.5 (stable) Aug/30/2022 09:25:53 
                   CRS328-24P-4S+" 
   system-caps=bridge,router system-caps-enabled=bridge,router 

 1 interface=ether1,Bridge-LAN address=192.168.12.64 address4=192.168.12.64 
   mac-address=48:8F:5A:20:B8:2D identity="###-2f11-AP" platform="MikroTik" 
   version="7.5 (stable) Aug/30/2022 09:25:53" unpack=none age=3s 
   uptime=3w3d10h42m25s software-id="MP13-LEQ2" board="RBcAPGi-5acD2nD" 
   ipv6=yes interface-name="bridge1/ether1" system-caps="" 
   system-caps-enabled="" 

 2 interface=ether2,Bridge-LAN address=192.168.12.20 address4=192.168.12.20 
   mac-address=74:4D:28:D3:5F:78 identity="###-2F-1-SW1" platform="MikroTik" 
   version="7.5 (stable) Aug/30/2022 09:25:53" unpack=none age=11s 
   uptime=3w2d10h36m57s software-id="5K0P-V6JC" board="CRS328-24P-4S+" 
   interface-name="bridge/ether24-Uplink" 
   system-description="MikroTik RouterOS 7.5 (stable) Aug/30/2022 09:25:53 
                   CRS328-24P-4S+" 
   system-caps=bridge,router system-caps-enabled=bridge,router 

 3 interface=ether2,Bridge-LAN address=192.168.12.21 address4=192.168.12.21 
   mac-address=C4:AD:34:73:09:9B identity="###-2F-7-SW1" platform="MikroTik" 
   version="7.4.1 (stable) Aug/04/2022 11:48:11" unpack=none age=3s 
   uptime=8w6d23h49m51s software-id="S4CI-QGRF" board="CRS112-8P-4S" ipv6=yes 
   interface-name="bridge/ether1-uplink" system-caps="" 
   system-caps-enabled="" 

 4 interface=ether2,Bridge-LAN address=192.168.12.69 address4=192.168.12.69 
   mac-address=C4:AD:34:5C:04:68 identity="###-2F-1-AP" platform="MikroTik" 
   version="7.5 (stable) Aug/30/2022 09:25:53" unpack=none age=3s 
   uptime=3w3d10h42m28s software-id="N3G7-NF8P" board="RBcAPGi-5acD2nD" 
   ipv6=yes interface-name="bridge/ether1" system-caps="" 
   system-caps-enabled="" 

 5 interface=ether2,Bridge-LAN address=192.168.12.130 address4=192.168.12.130 
   mac-address=D4:CA:6D:07:32:4C identity="Test\" platform="MikroTik" 
   version="7.6beta7 (development) Sep/16/2022 06:27:32" unpack=none age=12s 
   uptime=3w2d5h42m36s software-id="F9DB-EYMC" board="RB951G-2HnD" ipv6=yes 
   interface-name="bridge1/ether1" system-caps="" system-caps-enabled="" 

 6 interface=ether3,Bridge-LAN mac-address=00:04:13:75:1A:A4 identity="snom715" 
   platform="" version="" unpack=none age=17s interface-name="NET PORT" 
   system-description="snom;snom715-SIP 8.8.3.32;lid:8.8.3.32" 
   system-caps=bridge,telephone system-caps-enabled=bridge,telephone 

 7 interface=ether5-WAN,Bridge-LAN mac-address=70:4F:57:F9:51:CB 
   identity="###002b_a1\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\
         00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\0
         0\00\00\00\00\00\00\00\00\00\00\00\00" 
   platform="" version="" unpack=none age=28s 
   interface-name="GigabitEthernet1/0/6" 
   system-description="JetStream 24-Port Gigabit L2 Managed Switch with 4 SFP 
                   Slots" 
   system-caps=bridge,router system-caps-enabled=bridge,router 

 8 interface=ether5-WAN,Bridge-LAN address=192.168.12.62 address4=192.168.12.62 
   mac-address=6C:3B:6B:14:56:33 identity="###-1F35-AP" platform="MikroTik" 
   version="7.3.1 (stable) Jun/09/2022 08:58:15" unpack=none age=28s 
   uptime=17w2d20h3m24s software-id="10WF-473R" board="RB941-2nD" ipv6=yes 
   interface-name="bridge1/ether3" system-caps="" system-caps-enabled="" 

 9 interface=ether5-WAN,Bridge-LAN address=192.168.12.65 address4=192.168.12.65 
   mac-address=6C:3B:6B:14:57:C1 identity="###-2F-24-AP" platform="MikroTik" 
   version="7.4.1 (stable) Aug/04/2022 11:48:11" unpack=none age=42s 
   uptime=8w6d23h42m10s software-id="8V23-1SYM" board="RB941-2nD" ipv6=yes 
   interface-name="bridge1/ether1" system-caps="" system-caps-enabled="" 

10 interface=ether5-WAN,Bridge-LAN address=192.168.12.66 address4=192.168.12.66 
   mac-address=64:D1:54:61:6F:91 identity="###-1F-LAB-AP" platform="MikroTik" 
   version="7.4.1 (stable) Aug/04/2022 11:48:11" unpack=none age=11s 
   uptime=8w6d23h42m12s software-id="H9NH-QLEZ" board="RB941-2nD" ipv6=yes 
   interface-name="bridge1/ether1" system-caps="" system-caps-enabled="" 

11 interface=ether5-WAN,Bridge-LAN address=192.168.12.67 address4=192.168.12.67 
   mac-address=2C:C8:1B:9F:85:7B identity="###-1f29-ap" platform="MikroTik" 
   version="7.5 (stable) Aug/30/2022 09:25:53" unpack=none age=50s 
   uptime=3w3d10h41m28s software-id="44EG-MSNG" board="RBcAPGi-5acD2nD" 
   ipv6=yes interface-name="bridge1/ether1" system-caps="" 
   system-caps-enabled="" 

12 interface=ether6,Bridge-LAN address=10.2.1.55 address4=10.2.1.55 
   mac-address=64:16:7F:A4:07:4C identity="Polycom VVX 400" platform="" 
   version="" unpack=none age=0s interface-name="1" 
   system-description="Polycom;VVX-VVX_400;3111-46157-002,3;SIP/5.9.6.2996/30-
                   Jan-21 15:28;UP/5.9.7.42880/30-Jan-21 15:43;" 
   system-caps=bridge,telephone system-caps-enabled=telephone 

13 interface=ether8,Bridge-LAN mac-address=00:04:13:75:1A:98 identity="snom715" 
   platform="" version="" unpack=none age=4s interface-name="NET PORT" 
   system-description="snom;snom715-SIP 8.8.3.32;lid:8.8.3.32" 
   system-caps=bridge,telephone system-caps-enabled=bridge,telephone 

14 interface=ether8,Bridge-LAN mac-address=00:04:13:A5:26:2F identity="snom715" 
   platform="" version="" unpack=none age=48s interface-name="NET PORT" 
   system-description="snom;snom715-SIP 8.8.3.32;lid:8.8.3.32" 
   system-caps=bridge,telephone system-caps-enabled=bridge,telephone 

15 interface=ether8,Bridge-LAN address=192.168.12.7 address4=192.168.12.7 
   mac-address=00:04:F2:9E:47:9A identity="Lync Phone Edition - 9e479a" 
   platform="" version="" unpack=none age=50s 
   system-description="Lync Phone Edition - POLYCOM_CX600_Rev-5" 
   system-caps=telephone system-caps-enabled=telephone 

16 interface=ether8,Bridge-LAN address=192.168.12.61 address4=192.168.12.61 
   mac-address=6C:3B:6B:16:8F:53 identity="###-2F-27-AP" platform="MikroTik" 
   version="7.4.1 (stable) Aug/04/2022 11:48:11" unpack=none age=9s 
   uptime=8w6d23h46m5s software-id="BHXV-20RN" board="RB941-2nD" 
   interface-name="bridge1/ether4" 
   system-description="MikroTik RouterOS 7.4.1 (stable) Aug/04/2022 11:48:11 
                   RB941-2nD" 
   system-caps=bridge,router system-caps-enabled=bridge,router 

17 interface=ether9,Bridge-LAN mac-address=00:04:13:74:A6:64 identity="snom710" 
   platform="" version="" unpack=none age=40s interface-name="NET PORT" 
   system-description="snom;snom710-SIP 8.8.2.21;lid:8.8.2.21" 
   system-caps=bridge,telephone system-caps-enabled=bridge,telephone 

18 interface=ether9,Bridge-LAN mac-address=00:04:13:74:C2:17 identity="snom710" 
   platform="" version="" unpack=none age=15s interface-name="NET PORT" 
   system-description="snom;snom710-SIP 8.8.3.32;lid:8.8.3.32" 
   system-caps=bridge,telephone system-caps-enabled=bridge,telephone 

19 interface=ether9,Bridge-LAN mac-address=00:04:13:75:44:0C identity="snom715" 
   platform="" version="" unpack=none age=29s interface-name="NET PORT" 
   system-description="snom;snom715-SIP 8.8.3.32;lid:8.8.3.32" 
   system-caps=bridge,telephone system-caps-enabled=bridge,telephone 

20 interface=ether9,Bridge-LAN mac-address=00:04:13:A5:26:FB identity="snom715" 
   platform="" version="" unpack=none age=29s interface-name="NET PORT" 
   system-description="snom;snom715-SIP 8.8.3.32;lid:8.8.3.32" 
   system-caps=bridge,telephone system-caps-enabled=bridge,telephone 

21 interface=ether9,Bridge-LAN mac-address=00:04:13:A5:27:9C identity="snom715" 
   platform="" version="" unpack=none age=49s interface-name="NET PORT" 
   system-description="snom;snom715-SIP 8.8.3.32;lid:8.8.3.32" 
   system-caps=bridge,telephone system-caps-enabled=bridge,telephone 

22 interface=ether9,Bridge-LAN address=192.168.12.63 address4=192.168.12.63 
   mac-address=6C:3B:6B:14:55:F0 identity="###-2F-12-AP" platform="MikroTik" 
   version="7.4.1 (stable) Aug/04/2022 11:48:11" unpack=none age=2s 
   uptime=8w6d23h52m19s software-id="FBHH-KUH2" board="RB941-2nD" 
   interface-name="bridge1/ether1" 
   system-description="MikroTik RouterOS 7.4.1 (stable) Aug/04/2022 11:48:11 
                   RB941-2nD" 
   system-caps=bridge,router system-caps-enabled=bridge,router 

23 interface=ipip-###ograd address=10.1.1.41 address4=10.1.1.41 
   identity="###-gw1" platform="MikroTik" 
   version="7.5 (stable) Aug/30/2022 09:25:53" unpack=none age=7s 
   uptime=3w4d10h47m37s software-id="WMTD-QCJW" board="RB750Gr3" ipv6=yes 
   interface-name="ipip-###cow" system-caps="" system-caps-enabled="" 

24 interface=ipip-###alin address=10.1.1.53 address4=10.1.1.53 
   identity="###-gw1" platform="MikroTik" 
   version="7.5 (stable) Aug/30/2022 09:25:53" unpack=none age=42s 
   uptime=5d15h23s software-id="1J9S-00L0" board="RB750Gr3" ipv6=yes 
   interface-name="ipip-###cow" system-caps="" system-caps-enabled="" 

25 interface=vlan2-2ndWAN mac-address=74:4D:28:D3:5F:61 identity="###-2F-1-SW1" 
   platform="MikroTik" version="7.5 (stable) Aug/30/2022 09:25:53" 
   unpack=none age=12s uptime=3w2d10h36m57s software-id="5K0P-V6JC" 
   board="CRS328-24P-4S+" ipv6=yes interface-name="vlan1" system-caps="" 
   system-caps-enabled="" 

26 interface=vlan2-2ndWAN address=10.50.50.1 address4=10.50.50.1 
   mac-address=CC:2D:E0:DB:7E:30 identity="###-GW2" platform="MikroTik" 
   version="7.5 (stable) Aug/30/2022 09:25:53" unpack=none age=58s 
   uptime=2w5d5h51m33s software-id="BU7J-BHLY" board="RBwAPR-2nD" ipv6=yes 
   interface-name="ether1" system-caps="" system-caps-enabled="" 
```
