### ISSUE TITLE
napalm_ros.query  error

### ISSUE THREAD

**Issue by SerhiiZahuba** [napalm-automation-community/napalm-ros#99]
After updating the module, I get an error related to napalm_ros.query . But I can't find the napalm_ros.query module.

``
(venv) [root@Inventory netbox]# napalm --user admin --vendor napalm_ros 91.1.1.1 call get_config
Enter password: 
2022-07-25 19:09:10,286 - napalm - ERROR - get_network_driver - Failed: No module named 'napalm_ros.query'

================= Traceback =================

Traceback (most recent call last):
  File "/opt/netbox/venv/bin/napalm", line 8, in <module>
    sys.exit(main())
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/base/clitools/cl_napalm.py", line 308, in main
    run_tests(args)
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/base/clitools/cl_napalm.py", line 268, in run_tests
    driver = call_get_network_driver(args.vendor)
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/base/clitools/cl_napalm.py", line 27, in wrapper
    r = func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/base/clitools/cl_napalm.py", line 170, in call_get_network_driver
    return get_network_driver(vendor)
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/base/__init__.py", line 95, in get_network_driver
    raise e
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm/base/__init__.py", line 86, in get_network_driver
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm_ros/__init__.py", line 7, in <module>
    from napalm_ros.ros import ROSDriver
  File "/opt/netbox/venv/lib/python3.9/site-packages/napalm_ros/ros.py", line 37, in <module>
    from napalm_ros.query import (
ModuleNotFoundError: No module named 'napalm_ros.query'
```

**Comment by luqasz** [comment]
Module is [here](https://github.com/napalm-automation-community/napalm-ros/blob/master/napalm_ros/query.py).

Provide information about:
* napalm version
* napalm-ros version
* librouteros version

And use proper formatting in your traceback paste.

**Comment by SerhiiZahuba** [comment]
Thank you. I'm sorry. Added information below.


napalm version - 4.0.0
napalm-ros  - 1.0.1
librouteros - 3.2.1


`napalm --user admin --vendor napalm_ros 91.1.1.1 call get_config`

Now I'm getting another error


`{
    "running": "expected end of command (line 1 column 14)\n",
    "candidate": "expected end of command (line 1 column 14)\n",
    "startup": "expected end of command (line 1 column 14)\n"
}
`

**Comment by luqasz** [comment]
`napalm-ros` with `get_config()` isn't released yet so how did you execute `get_config` ?

**Comment by SerhiiZahuba** [comment]
I copied all your changes to get_config. I thought it would work. If you have information - please write when the new version will be released.

**Comment by luqasz** [comment]
It's released.

**Comment by SerhiiZahuba** [comment]
after update to 1.1.0 i see an erorr


Enter password: 
{
    "running": "expected end of command (line 1 column 14)\n",
    "candidate": "expected end of command (line 1 column 14)\n",
    "startup": "expected end of command (line 1 column 14)\n"
}

**Comment by luqasz** [comment]
Which version of routeros are you running on destination host ?

**Comment by SerhiiZahuba** [comment]
6.48.5

**Comment by luqasz** [comment]
Does `/export terse` work for you in regular ssh session ?

**Comment by SerhiiZahuba** [comment]
Yes. Works.

**Comment by luqasz** [comment]
Hmm. Try to modify https://github.com/napalm-automation-community/napalm-ros/blob/master/napalm_ros/ros.py#L372
and set
```
command = "/export terse"
```
note `/`

**Comment by SerhiiZahuba** [comment]
did not help

```
Enter password: 
{
    "running": "expected end of command (line 1 column 15)\n",
    "candidate": "expected end of command (line 1 column 15)\n",
    "startup": "expected end of command (line 1 column 15)\n"
}

```

**Comment by luqasz** [comment]
Hmm Then I don't know what's the problem. 🤷
